version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: radikal-backend
    ports:
      - "8000:8000"
    environment:
      - DEVICE=cpu
      - MODEL_PATH=/app/models/checkpoints/best_model.pth
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - MAKERKIT_API_URL=${MAKERKIT_API_URL:-http://frontend:3000}
    volumes:
      - ./backend/models:/app/models
      - ./backend/data:/app/data
      - ./backend/exports:/app/exports
      - ./backend/logs:/app/logs
    networks:
      - radikal-network
    depends_on:
      - mlflow
    restart: unless-stopped

  # MLflow tracking server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.8.1
    container_name: radikal-mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - mlflow-data:/mlflow
    networks:
      - radikal-network
    command: mlflow server --host 0.0.0.0 --port 5000
    restart: unless-stopped

  # Frontend Makerkit/Next.js service (placeholder)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: radikal-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=production
    networks:
      - radikal-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  radikal-network:
    driver: bridge

volumes:
  mlflow-data:
    driver: local
