artifact_location: file:///C:/Users/Amine EL-Hend/Documents/GitHub/RadiKal/backend/runs/mlflow/809728953514087462
creation_time: 1760910241785
experiment_id: '809728953514087462'
last_update_time: 1760910241785
lifecycle_stage: active
name: models/yolo
