artifact_uri: file:///C:/Users/Amine EL-Hend/Documents/GitHub/RadiKal/backend/runs/mlflow/809728953514087462/4ddd6a5f044348218f812170f224555b/artifacts
end_time: 1761168438235
entry_point_name: ''
experiment_id: '809728953514087462'
lifecycle_stage: active
run_id: 4ddd6a5f044348218f812170f224555b
run_name: classification_defect_focused
source_name: ''
source_type: 4
source_version: ''
start_time: 1761166885897
status: 3
tags: []
user_id: Amine EL-Hend
