artifact_location: file:///C:/Users/Amine EL-Hend/Documents/GitHub/RadiKal/backend/runs/mlflow/0
creation_time: 1760910241742
experiment_id: '0'
last_update_time: 1760910241742
lifecycle_stage: active
name: Default
